collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4808511
  brandStrength: 0.5501939
  lightness: 1
  brandColors:
    - '#AEACA0'
    - '#DBDCE1'
    - '#C8C9CD'
    - '#A29F96'
    - '#939395'
  rhythmicContrast: 0
typography_spectrum: 0.2191489
layout_spectrum: 0
name: Metaspace
