layout_spectrum: 1
typography_spectrum: 0.2191489
color:
  saturation: 0.4787234
  lightness: 1
  brandStrength: 0.5501939
  brandColors:
    - '#AEACA0'
    - '#DBDCE1'
    - '#C8C9CD'
    - '#A29F96'
    - '#939395'
  rhythmicContrast: 0.8381765
name: Metaspace
